### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by xudadi001** [hulianyuyy/STGAT#10]
May i ask What is the specific meaning of 2s-STGAT and 4s-STGAT in the article, and what is the use of ensemble.py.

**Comment by hulianyuyy** [comment]
2s-STGAT refers to the ensemble of bone and joint streams. 4s-STGAT refers to the ensemble of joint, bone, joint-motion and bone-motions streams. You can set 'decouple_spatial' (False to True) option in config file to train bone stream. You can change 'num_skip_frame'(None to 1) to train joint-motion and bone-motion stream. Then combine the generated scores with `python train_val_test/ensemble.py`

**Comment by xudadi001** [comment]
感谢

**Comment by xudadi001** [comment]
请问如果我想要训练4s-STGAT，我需要将对应数据集的.yaml文件中的'decouple_spatial' 设置为True，将'num_skip_frame'设置为‘1’，对吗？
此外我该怎样处理数据集，来获得joint, bone, joint-motion streams, bone-motions streams所对应的预处理文件。

**Comment by hulianyuyy** [comment]
不需要额外预处理数据集，直接使用tran_joint.npy和val_joint.npy就行。将'decouple_spatial' 设置为Flase或True，将'num_skip_frame'设置为‘0或1’，两两组合分别训练四个模型得到结果，python train_val_test/ensemble.py融合四个模型的输出。

**Comment by xudadi001** [comment]
请问分开训练后会自动生成下面所需要的文件吗？
<img width="847" alt="1" src="https://user-images.githubusercontent.com/65487336/233826032-88dc287a-21fa-4cc7-b430-c3bba7efbceb.png">
我在按如下设置训练后分别训练后并未找到所对应的文件，是我的操作有什么问题吗。
![5}$L$P4G)ATR$RJ1J8~WPPK](https://user-images.githubusercontent.com/65487336/233826099-30337559-749e-4446-ab36-9e03ec6b01a6.png)

**Comment by hulianyuyy** [comment]
在work_dir下对应数据集的保存文件目录中有生成的score.pkl

**Comment by musrea** [comment]
First of all , Thank you for your great work.
Secondly, May I obtain the default settings in Model Parameters. Because I notice that using Temporal Attention set to false in  current version.
![image](https://github.com/hulianyuyy/STGAT/assets/29855592/8d22ce81-a2d8-4afd-9251-276790acd726)

**Comment by hulianyuyy** [comment]
The default setting is 'no temporal attention'. You can count the parameters directly.



---Original---
From: "Musrea Abdo ***@***.***&gt;
Date: Thu, Jun 15, 2023 23:06 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] Some questions (Issue #10)




 
First of all , Thank you for your great work.
 Secondly, May I obtain the default settings in Model Parameters. Because I notice that using Temporal Attention set to false in  current version.

**Comment by sencer4898** [comment]
Dear Lianyu,

Thank you for making the code available. I have some questions related to your code:

1. Is pre_trained_model and last_model have similar functionalities? (Except pre_trained_model is affected from ignore_weights)
2. 2. is ignore_weights['fc'] equivalent to include_top = False? (for training a task-specific last layer)
3. Are the scripts not data flexible (suitable to only NTU and kinetics)? (Because data_choose raises error otherwise)

Thanks in advance
