### ISSUE TITLE
How to train it with 2d data

### ISSUE THREAD

**Issue by MJCC-wht** [hulianyuyy/STGAT#13]
I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 3 to 2, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0

**Comment by hulianyuyy** [comment]
Sorry, what's the meaning of 2d data? It is a Rgb image?



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 12, 2023 15:33 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13)




 
I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 2 to 3, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0

**Comment by MJCC-wht** [comment]
> Sorry, what's the meaning of 2d data? It is a Rgb image?
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jun 12, 2023 15:33 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 2 to 3, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

yes, the input shape is (batch_size, 2, T, V, M)

**Comment by hulianyuyy** [comment]
This model is designed to handle skeleton data. For rgb data like rgb images, you can refer to other CNN models like ResNet for processing.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 12, 2023 15:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13)




  
Sorry, what's the meaning of 2d data? It is a Rgb image?
 …
 ---Original--- From: @.&gt; Date: Mon, Jun 12, 2023 15:33 PM To: @.&gt;; Cc: @.&gt;; Subject: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 2 to 3, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
yes, the input shape is (batch_size, 2, T, V, M)

**Comment by MJCC-wht** [comment]
> This model is designed to handle skeleton data. For rgb data like rgb images, you can refer to other CNN models like ResNet for processing.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jun 12, 2023 15:36 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) Sorry, what's the meaning of 2d data? It is a Rgb image? … ---Original--- From: @.&gt; Date: Mon, Jun 12, 2023 15:33 PM To: @.&gt;; Cc: @.&gt;; Subject: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 2 to 3, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; yes, the input shape is (batch_size, 2, T, V, M) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

I don't mean rgb images, it is also skeleton data, but the dimension is not 3, but 2. Like using HRNet to get the skelenton data of an action video.

**Comment by hulianyuyy** [comment]
Considering your issue, you could check if there are NaN values in the input data. They may hinder the training process.



---Original---
From: ***@***.***&gt;
Date: Mon, Jun 12, 2023 15:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13)




  
This model is designed to handle skeleton data. For rgb data like rgb images, you can refer to other CNN models like ResNet for processing.
 …
 ---Original--- From: @.&gt; Date: Mon, Jun 12, 2023 15:36 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) Sorry, what's the meaning of 2d data? It is a Rgb image? … ---Original--- From: @.&gt; Date: Mon, Jun 12, 2023 15:33 PM To: @.&gt;; Cc: @.&gt;; Subject: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 2 to 3, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; yes, the input shape is (batch_size, 2, T, V, M) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
I don't mean rgb images, it is also skeleton data, but the dimension is not 3, but 2. Like using HRNet to get the skelenton data of an action video.

**Comment by MJCC-wht** [comment]
> Considering your issue, you could check if there are NaN values in the input data. They may hinder the training process.
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Mon, Jun 12, 2023 15:43 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) This model is designed to handle skeleton data. For rgb data like rgb images, you can refer to other CNN models like ResNet for processing. … ---Original--- From: @.&gt; Date: Mon, Jun 12, 2023 15:36 PM To: @.&gt;; Cc: @.@.&gt;; Subject: Re: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) Sorry, what's the meaning of 2d data? It is a Rgb image? … ---Original--- From: @.&gt; Date: Mon, Jun 12, 2023 15:33 PM To: @.&gt;; Cc: @.&gt;; Subject: [hulianyuyy/STGAT] How to train it with 2d data (Issue #13) I change the data_path to 'train_joint_position_in_img.npy' and change the num_channel from 2 to 3, but in the training, there is a error 'NaN or Inf found in input tensor' and the train accuracy is almost 0 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; yes, the input shape is (batch_size, 2, T, V, M) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; I don't mean rgb images, it is also skeleton data, but the dimension is not 3, but 2. Like using HRNet to get the skelenton data of an action video. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

OK, thank you
